### ISSUE TITLE
Использовать семантичные имена

### ISSUE THREAD

**Issue by chmnkh** [Frolikow/UIkit#14]
Не нужно использовать имена чего-либо, подобные именам параметров в этом миксине:
```
mixin location(position1, position2)
```
Постарайся дать такое имя, чтобы не нужно было лезть в код, или пытаться делать какие-то предположения, чтобы узнать, что за position1, position2 и чем они отличаются. С правильным именем все это должно стать очевидно.

**Comment by chmnkh** [comment]
```
.location_menu_buttons_1
.location_menu_buttons_2
```
из той же серии

**Comment by chmnkh** [comment]
На будущее: старайся не делать миллион ишью в одном коммите, очень сложно проверять)
Если ты будешь только один коммит на ишью делать, можно будет просто по коммиту посмотреть что ты изменил и все, а найти что-либо по коммиту, который ты сделал, нереально просто.
Закрой ишью, как прочтешь.

**Comment by Frolikow** [comment]
Я после того как сделал коммит этот, увидел его объем и понял что сделал нехорошо)
