### ISSUE TITLE
Классы, которые используются в скриптах, должны начинаться с префикса js-*

### ISSUE THREAD

**Issue by prodderman** [Frolikow/UIkit#15]
https://github.com/Frolikow/UIkit/blob/35a9cb14a434d87bdda93db3691e57913763476e/src/modules/calendar/calendar.js#L3-L6
У тебя где то есть, а где то нет. Сделай, что бы везде было

**Comment by Geksanit** [comment]
![image](https://user-images.githubusercontent.com/31949379/45218047-67402980-b2d0-11e8-887c-c5c323537953.png)

**Comment by Geksanit** [comment]
messager.js тоже

**Comment by Frolikow** [comment]
Поторопился и сделал в один коммит с другим  [ишью](https://github.com/Frolikow/UIkit/commit/822ec3026a3eb092d95144318fc267ef7e9a4895)

**Comment by Geksanit** [comment]
закрывай ишью
