### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [Frolikow/UIkit#24]
Можешь пожалуйста выложить в инверсии макет и настройки perfect pixel, по которым верстался макет.

**Comment by Frolikow** [comment]
Вот скрины, если я правильно тебя понял)
![flatui psd](https://user-images.githubusercontent.com/25764783/45871313-653d9680-bdb7-11e8-98bd-d90216a918cc.png)
![image](https://user-images.githubusercontent.com/25764783/45871628-2825d400-bdb8-11e8-8810-f381333510bc.png)

**Comment by Geksanit** [comment]
В плагине включи инверсию, и прозрачность на половину. Будет видно отличия.

**Comment by chmnkh** [comment]
А что у тебя за процент в пай-чарте?)
![image](https://user-images.githubusercontent.com/18498637/45917052-cccc1280-be99-11e8-8f42-c93175a34566.png)

**Comment by ValentinAlexandrovich** [comment]
Нет в Pixel Perfect включи настройку Иверсия, и наложи маект для разработки, поверх своей страницы с макетом, а сюда выложи скрин.

**Comment by ValentinAlexandrovich** [comment]
![default](https://user-images.githubusercontent.com/31854808/45924242-3e04d780-bf25-11e8-80e2-720fa84a85be.jpg)

**Comment by ValentinAlexandrovich** [comment]
Такого расхождения с макетом явно не должно быть.

**Comment by ValentinAlexandrovich** [comment]
Подправь плиз мессадж блок и календарь по высоте блоки, а также блоки news, чтобы не было таких существенных отличий по ширине и высотам элементов, плюс блок видео должен подняться по расположению относительно макета.

**Comment by Frolikow** [comment]
![image](https://user-images.githubusercontent.com/25764783/46067979-44ec4e00-c1a2-11e8-9a0d-cf7a684fecfb.png)

![image](https://user-images.githubusercontent.com/25764783/46067867-06569380-c1a2-11e8-8e7e-146989c5508a.png)
