### ISSUE TITLE
Demo нужно сделать больше похожим на макет

### ISSUE THREAD

**Issue by Geksanit** [Frolikow/UIkit#6]
PerfectPixel - есть такой плагин в хроме, с ним можно наложить картинку на страницу и сравнить.

**Comment by kinda-neat** [comment]
Есть конкретное требование ко второму заданию 2: Все отступы и размеры элементов должны быть соблюдены, для этого во время работы используйте расширение PerfectPixel
У тебя же оно не выполнено

**Comment by Geksanit** [comment]
Нужно столько же кнопок. И обнови ветку gh-pages.

**Comment by Geksanit** [comment]
в Readme.md не открывается страница по ссылке. И должно быть две ссылки: одна на страницу по макету, вторая на твои кастомные страницы.
